// Domain types, generated by hand from CONTRACT.md §2 (enums) + §3 (data model).
// Keep field names EXACTLY as the contract specifies; the backend is the source of truth.

// ---------- Enums (§2) ----------
export type Role =
  | 'fsr'
  | 'asm'
  | 'regional_head'
  | 'warehouse_manager'
  | 'finance'
  | 'admin'
  | 'super_admin';

export type OutletStatus =
  | 'prospect'
  | 'pending_approval'
  | 'active'
  | 'dormant'
  | 'churned'
  | 'rejected';

export type OutletClass = 'A' | 'B' | 'C' | 'D';

export type OrderStatus =
  | 'draft'
  | 'submitted'
  | 'approved'
  | 'allocated'
  | 'dispatched'
  | 'delivered'
  | 'invoiced'
  | 'cancelled';

export type ReceivableStatus = 'open' | 'partially_paid' | 'paid' | 'overdue';

export type PaymentType = 'full' | 'partial' | 'credit';
export type PaymentMethod = 'cash' | 'upi' | 'cheque';

export type VisitOutcome = 'order_placed' | 'no_order';

export type ReasonCode =
  | 'not_interested'
  | 'no_shelf_space'
  | 'decision_pending'
  | 'owner_absent'
  | 'shop_closed'
  | 'price_issue'
  | 'sufficient_stock'
  | 'other';

export type CreditAction = 'warn' | 'block' | 'require_approval';
export type CreditResult = 'ok' | 'warn' | 'block' | 'approval_required';

export type SchemeType = 'slab' | 'bogo' | 'free_goods' | 'flat';

export type TerritoryType = 'region' | 'area' | 'beat';

// ---------- Shared shapes (§1) ----------
export interface GeoPoint {
  type: 'Point';
  coordinates: [number, number]; // [lng, lat]
}

export interface Paginated<T> {
  items: T[];
  total: number;
  page: number;
  page_size: number;
}

export interface ApiError {
  detail: string | { loc: (string | number)[]; msg: string; type: string }[];
}

interface BaseDoc {
  id: string;
  tenant_id: string;
  created_at: string;
  updated_at: string;
}

// ---------- tenants / config (§3) ----------
export interface CustomFieldDef {
  key: string;
  label: string;
  type: 'text' | 'number' | 'boolean' | 'select';
  required: boolean;
  options?: string[];
}

export interface CreditPolicy {
  over_limit: CreditAction;
  overdue: CreditAction;
}

export interface TenantConfig {
  geofence_radius_m: number;
  gps_accuracy_threshold_m: number;
  credit_policy: CreditPolicy;
  reason_codes: ReasonCode[];
  outlet_custom_fields: CustomFieldDef[];
  dormant_days: number;
}

export interface Tenant extends BaseDoc {
  name: string;
  config: TenantConfig;
}

// ---------- users (§3) ----------
export interface User extends BaseDoc {
  name: string;
  email: string;
  phone?: string;
  role: Role;
  territory_ids: string[];
  manager_id?: string | null;
  status: 'active' | 'disabled';
  push_tokens?: string[];
}

// ---------- territories / routes (§3) ----------
export interface Territory extends BaseDoc {
  name: string;
  parent_id?: string | null;
  type: TerritoryType;
  assigned_user_ids: string[];
}

export interface Route extends BaseDoc {
  name: string;
  rep_id: string;
  asm_id?: string;
  territory_id: string;
  outlet_ids: string[];
  day_of_week?: number; // 0-6
  cycle?: string;
  active: boolean;
}

// ---------- outlets (§3) ----------
export interface OutletProfile {
  shop_type?: string;
  owner_name?: string;
  owner_phone?: string;
  gst?: string;
  pan?: string;
  refrigeration?: boolean;
  shelf_space?: string;
  competitor_brands?: string[];
  est_monthly_volume?: number;
  preferred_order_day?: string;
  [custom: string]: unknown;
}

export interface Outlet extends BaseDoc {
  name: string;
  code: string;
  location: GeoPoint;
  geofence_radius_m?: number | null;
  photos: string[];
  profile: OutletProfile;
  outlet_class: OutletClass;
  status: OutletStatus;
  credit_limit: number;
  outstanding: number;
  assigned_rep_id?: string | null;
  territory_id?: string | null;
  created_by?: string;
  approved_by?: string | null;
  last_order_at?: string | null;
  last_visit_at?: string | null;
  next_visit_date?: string | null;
  client_uuid?: string;
}

// ---------- visits (§3) ----------
export interface VisitCheckIn {
  location: GeoPoint;
  accuracy: number;
  timestamp: string;
  photo_url?: string;
  in_fence: boolean;
  distance_m: number;
  is_mock: boolean;
  flag_reason?: string | null;
}

export interface VisitCheckOut {
  location: GeoPoint;
  timestamp: string;
}

export interface VisitPitch {
  demoed_sku_ids: string[];
  notes?: string;
  photos?: string[];
}

export interface Visit extends BaseDoc {
  outlet_id: string;
  rep_id: string;
  route_id?: string | null;
  check_in: VisitCheckIn;
  check_out?: VisitCheckOut | null;
  duration_min?: number | null;
  outcome?: VisitOutcome | null;
  reason_code?: ReasonCode | null;
  order_id?: string | null;
  pitch?: VisitPitch | null;
  next_visit_date?: string | null;
  client_uuid?: string;
}

// ---------- skus / catalog (§3) ----------
export interface Sku extends BaseDoc {
  name: string;
  code: string;
  category: string;
  pack_size: string;
  unit: string;
  mrp: number;
  ptr: number; // price-to-retailer
  ptd: number; // price-to-distributor
  moq: number;
  hsn: string;
  gst_rate: number;
  image_url?: string;
  active: boolean;
}

export interface CatalogSku extends Sku {
  qty_available: number;
  orderable: boolean;
}

// ---------- warehouses / inventory (§3) ----------
export interface Warehouse extends BaseDoc {
  name: string;
  code: string;
  location?: GeoPoint | null;
  territory_id?: string | null;
}

export interface Inventory extends BaseDoc {
  sku_id: string;
  sku_name?: string;
  sku_code?: string;
  warehouse_id: string;
  warehouse_name?: string;
  qty_available: number;
  qty_reserved: number;
  reorder_level: number;
}

// ---------- orders (§3) ----------
export interface OrderLineItem {
  sku_id: string;
  sku_name: string;
  qty: number;
  unit_price: number;
  discount_pct: number;
  discount_amt: number;
  line_total: number;
  gst_rate: number;
  gst_amt: number;
}

export interface CreditCheck {
  limit: number;
  outstanding: number;
  order_value: number;
  result: CreditResult;
  overridden_by?: string | null;
}

export interface StatusHistoryEntry {
  status: OrderStatus;
  at: string;
  by: string;
  by_name?: string;
  note?: string;
}

export interface Order extends BaseDoc {
  code: string;
  outlet_id: string;
  outlet_name?: string;
  rep_id: string;
  rep_name?: string;
  visit_id?: string | null;
  warehouse_id: string;
  warehouse_name?: string;
  line_items: OrderLineItem[];
  subtotal: number;
  discount_total: number;
  gst_total: number;
  total: number;
  status: OrderStatus;
  credit_check: CreditCheck;
  status_history: StatusHistoryEntry[];
  expected_delivery_date?: string | null;
  client_uuid?: string;
  idempotency_key?: string;
}

// ---------- payments / receivables (§3) ----------
export interface CollectionEntry {
  amount: number;
  method: PaymentMethod;
  reference?: string;
  at: string;
  by: string;
}

export interface Payment extends BaseDoc {
  order_id: string;
  order_code?: string;
  outlet_id: string;
  outlet_name?: string;
  type: PaymentType;
  method: PaymentMethod;
  amount_collected: number;
  balance: number;
  credit_days: number;
  due_date?: string | null;
  reference?: string;
  collected_by?: string;
  status: ReceivableStatus;
  collections: CollectionEntry[];
  client_uuid?: string;
}

export interface AgingBucket {
  bucket: '0-30' | '31-60' | '60+';
  total: number;
  count: number;
  outlets: { outlet_id: string; outlet_name: string; amount: number; days: number }[];
}

export interface ReceivablesAging {
  buckets: AgingBucket[];
  total_outstanding: number;
}

// ---------- audit / notifications (§3) ----------
export interface AuditLog extends BaseDoc {
  actor_id: string;
  actor_name?: string;
  action: string;
  entity_type: string;
  entity_id: string;
  before?: Record<string, unknown> | null;
  after?: Record<string, unknown> | null;
  ip?: string;
  timestamp: string;
}

export interface Notification extends BaseDoc {
  user_id: string;
  type: string;
  title: string;
  body: string;
  data?: Record<string, unknown>;
  read: boolean;
}

// ---------- analytics (§4) ----------
export interface AnalyticsSummary {
  coverage_pct: number;
  coverage_prev_pct?: number;
  strike_rate_pct: number;
  strike_rate_prev_pct?: number;
  sales_mtd: number;
  sales_prev?: number;
  outstanding_total: number;
  outstanding_overdue?: number;
  active_outlets?: number;
  pending_approvals?: number;
}

export interface SalesGroupRow {
  key: string;
  label: string;
  current: number;
  prior: number;
  growth_pct: number;
}

export interface SalesAnalytics {
  group_by: 'sku' | 'rep' | 'region' | 'category';
  rows: SalesGroupRow[];
  current_total: number;
  prior_total: number;
  growth_pct: number;
}

export interface CoveragePoint {
  date: string;
  planned: number;
  visited: number;
  coverage_pct: number;
}

export interface CoverageAnalytics {
  overall_coverage_pct: number;
  outlet_coverage_pct: number;
  series: CoveragePoint[];
  by_rep: { rep_id: string; rep_name: string; coverage_pct: number; visited: number; planned: number }[];
}

export interface StrikeRateRow {
  rep_id: string;
  rep_name: string;
  visits: number;
  orders: number;
  strike_rate_pct: number;
}

export interface StrikeRateAnalytics {
  overall_pct: number;
  by_rep: StrikeRateRow[];
}

export interface LiveOpsRep {
  rep_id: string;
  rep_name: string;
  visits_today: number;
  planned_today: number;
  route_progress_pct: number;
  last_location?: GeoPoint | null;
  last_seen_at?: string | null;
  last_outlet_name?: string | null;
  status: 'active' | 'idle' | 'offline';
}

export interface LiveOps {
  reps: LiveOpsRep[];
  server_time: string;
}

// ---------- auth (§4) ----------
export interface LoginResponse {
  access_token: string;
  token_type: 'bearer';
  user: User;
}
