// Domain types, generated by hand from CONTRACT.md §2 (enums) + §3 (data model).
// Keep field names EXACTLY as the contract specifies; the backend is the source of truth.

// ---------- Enums (§2) ----------
export type Role =
  | 'fsr'
  | 'asm'
  | 'regional_head'
  | 'warehouse_manager'
  | 'finance'
  | 'store_manager'
  | 'admin'
  | 'super_admin';

export type OutletStatus =
  | 'prospect'
  | 'pending_approval'
  | 'active'
  | 'dormant'
  | 'churned'
  | 'rejected';

export type OutletClass = 'A' | 'B' | 'C' | 'D';

export type OrderStatus =
  | 'draft'
  | 'submitted'
  | 'approved'
  | 'allocated'
  | 'dispatched'
  | 'delivered'
  | 'invoiced'
  | 'cancelled';

export type ReceivableStatus = 'open' | 'partially_paid' | 'paid' | 'overdue';

export type PaymentType = 'full' | 'partial' | 'credit';
export type PaymentMethod = 'cash' | 'upi' | 'cheque';

export type VisitOutcome = 'order_placed' | 'no_order';

export type ReasonCode =
  | 'not_interested'
  | 'no_shelf_space'
  | 'decision_pending'
  | 'owner_absent'
  | 'shop_closed'
  | 'price_issue'
  | 'sufficient_stock'
  | 'other';

export type CreditAction = 'warn' | 'block' | 'require_approval';
export type CreditResult = 'ok' | 'warn' | 'block' | 'approval_required';

export type SchemeType = 'slab' | 'bogo' | 'free_goods' | 'flat';

export type TerritoryType = 'region' | 'area' | 'beat';

// ---------- Shared shapes (§1) ----------
export interface GeoPoint {
  type: 'Point';
  coordinates: [number, number]; // [lng, lat]
}

export interface Paginated<T> {
  items: T[];
  total: number;
  page: number;
  page_size: number;
}

export interface ApiError {
  detail: string | { loc: (string | number)[]; msg: string; type: string }[];
}

interface BaseDoc {
  id: string;
  tenant_id: string;
  created_at: string;
  updated_at: string;
}

// ---------- tenants / config (§3) ----------
export interface CustomFieldDef {
  key: string;
  label: string;
  type: 'text' | 'number' | 'boolean' | 'select';
  required: boolean;
  options?: string[];
}

export interface CreditPolicy {
  over_limit: CreditAction;
  overdue: CreditAction;
}

export interface TenantConfig {
  geofence_radius_m: number;
  gps_accuracy_threshold_m: number;
  credit_policy: CreditPolicy;
  // Default credit cap applied to outlets reps self-onboard in the field.
  new_outlet_credit_limit: number;
  reason_codes: ReasonCode[];
  outlet_custom_fields: CustomFieldDef[];
  dormant_days: number;
}

export interface Tenant extends BaseDoc {
  name: string;
  config: TenantConfig;
}

// ---------- users (§3) ----------
export interface User extends BaseDoc {
  name: string;
  email: string;
  phone?: string;
  role: Role;
  territory_ids: string[];
  manager_id?: string | null;
  status: 'active' | 'disabled';
  push_tokens?: string[];
}

// ---------- territories / routes (§3) ----------
export interface Territory extends BaseDoc {
  name: string;
  parent_id?: string | null;
  type: TerritoryType;
  assigned_user_ids: string[];
}

export interface Route extends BaseDoc {
  name: string;
  rep_id: string;
  asm_id?: string;
  territory_id: string;
  outlet_ids: string[];
  day_of_week?: number; // 0-6
  cycle?: string;
  active: boolean;
}

// ---------- outlets (§3) ----------
export interface OutletProfile {
  shop_type?: string;
  owner_name?: string;
  owner_phone?: string;
  gst?: string;
  pan?: string;
  refrigeration?: boolean;
  shelf_space?: string;
  competitor_brands?: string[];
  est_monthly_volume?: number;
  preferred_order_day?: string;
  [custom: string]: unknown;
}

export interface Outlet extends BaseDoc {
  name: string;
  code: string;
  location: GeoPoint;
  geofence_radius_m?: number | null;
  photos: string[];
  profile: OutletProfile;
  outlet_class: OutletClass;
  status: OutletStatus;
  credit_limit: number;
  outstanding: number;
  assigned_rep_id?: string | null;
  territory_id?: string | null;
  created_by?: string;
  approved_by?: string | null;
  last_order_at?: string | null;
  last_visit_at?: string | null;
  next_visit_date?: string | null;
  client_uuid?: string;
}

/**
 * A single plottable outlet from `GET /outlets/geo` (OUTLET_MAP_CONTRACT §1).
 *
 * This is a PROJECTION, not an `Outlet`: it carries only what the map needs.
 * Coordinates arrive as explicit `lng` / `lat` scalars — NOT a `GeoPoint`
 * `[lng, lat]` tuple — precisely so nobody re-introduces the classic swap bug.
 */
export interface OutletGeoItem {
  id: string;
  name: string;
  code: string;
  lng: number;
  lat: number;
  status: OutletStatus;
  outlet_class: OutletClass;
  geofence_radius_m?: number | null;
  assigned_rep_id?: string | null;
  assigned_rep_name?: string | null;
  outstanding: number;
  last_visit_at?: string | null;
}

/**
 * `GET /outlets/geo` envelope. Non-paginated and territory-scoped: `items` is
 * EVERY outlet in the caller's scope, up to a server-side cap.
 *
 * The three counters exist so the UI can be honest instead of silently lying:
 * - `total`          — matched in scope (may exceed `returned`)
 * - `truncated`      — the server hit its cap; the map is NOT showing everything
 * - `without_coords` — outlets that exist but have no location and so cannot be
 *                      plotted at all. They are excluded from `items` and from
 *                      `total`'s plottable meaning — surface them, never drop them.
 */
export interface OutletGeoResponse {
  items: OutletGeoItem[];
  total: number;
  returned: number;
  truncated: boolean;
  without_coords: number;
}

// ---------- visits (§3) ----------
export interface VisitCheckIn {
  location: GeoPoint;
  accuracy: number;
  timestamp: string;
  photo_url?: string;
  in_fence: boolean;
  distance_m: number;
  is_mock: boolean;
  flag_reason?: string | null;
}

export interface VisitCheckOut {
  location: GeoPoint;
  timestamp: string;
}

export interface VisitPitch {
  demoed_sku_ids: string[];
  notes?: string;
  photos?: string[];
}

export interface Visit extends BaseDoc {
  outlet_id: string;
  rep_id: string;
  route_id?: string | null;
  check_in: VisitCheckIn;
  check_out?: VisitCheckOut | null;
  duration_min?: number | null;
  outcome?: VisitOutcome | null;
  reason_code?: ReasonCode | null;
  order_id?: string | null;
  pitch?: VisitPitch | null;
  next_visit_date?: string | null;
  client_uuid?: string;
}

// ---------- skus / catalog (§3) ----------
export interface Sku extends BaseDoc {
  name: string;
  code: string;
  category: string;
  pack_size: string;
  unit: string;
  mrp: number;
  ptr: number; // price-to-retailer
  ptd: number; // price-to-distributor
  moq: number;
  hsn: string;
  gst_rate: number;
  image_url?: string;
  active: boolean;
}

export interface CatalogSku extends Sku {
  qty_available: number;
  orderable: boolean;
}

// ---------- warehouses / inventory (§3) ----------
export interface Warehouse extends BaseDoc {
  name: string;
  code: string;
  location?: GeoPoint | null;
  territory_id?: string | null;
}

export interface Inventory extends BaseDoc {
  sku_id: string;
  sku_name?: string;
  sku_code?: string;
  warehouse_id: string;
  warehouse_name?: string;
  qty_available: number;
  qty_reserved: number;
  reorder_level: number;
}

// ---------- orders (§3) ----------
export interface OrderLineItem {
  sku_id: string;
  sku_name: string;
  qty: number;
  unit_price: number;
  discount_pct: number;
  discount_amt: number;
  line_total: number;
  gst_rate: number;
  gst_amt: number;
}

export interface CreditCheck {
  limit: number;
  outstanding: number;
  order_value: number;
  result: CreditResult;
  overridden_by?: string | null;
}

export interface StatusHistoryEntry {
  status: OrderStatus;
  at: string;
  by: string;
  by_name?: string;
  note?: string;
}

export interface Order extends BaseDoc {
  code: string;
  outlet_id: string;
  outlet_name?: string;
  rep_id: string;
  rep_name?: string;
  visit_id?: string | null;
  warehouse_id: string;
  warehouse_name?: string;
  line_items: OrderLineItem[];
  subtotal: number;
  discount_total: number;
  gst_total: number;
  total: number;
  status: OrderStatus;
  credit_check: CreditCheck;
  status_history: StatusHistoryEntry[];
  expected_delivery_date?: string | null;
  client_uuid?: string;
  idempotency_key?: string;
}

// ---------- payments / receivables (§3) ----------
export interface CollectionEntry {
  amount: number;
  method: PaymentMethod;
  reference?: string;
  at: string;
  by: string;
}

export interface Payment extends BaseDoc {
  order_id: string;
  order_code?: string;
  outlet_id: string;
  outlet_name?: string;
  type: PaymentType;
  method: PaymentMethod;
  amount_collected: number;
  balance: number;
  credit_days: number;
  due_date?: string | null;
  reference?: string;
  collected_by?: string;
  status: ReceivableStatus;
  collections: CollectionEntry[];
  client_uuid?: string;
}

export interface AgingBucket {
  bucket: '0-30' | '31-60' | '60+';
  total: number;
  count: number;
  outlets: { outlet_id: string; outlet_name: string; amount: number; days: number }[];
}

export interface ReceivablesAging {
  buckets: AgingBucket[];
  total_outstanding: number;
}

// ---------- audit / notifications (§3) ----------
export type AuditOutcome = 'success' | 'failure';

export interface AuditLog extends BaseDoc {
  actor_id: string;
  actor_name?: string | null;
  actor_email?: string | null;
  actor_role?: string | null;
  action: string;
  entity_type: string;
  entity_id: string;
  before?: Record<string, unknown> | null;
  after?: Record<string, unknown> | null;
  // Request-source entries (captured by the catch-all audit middleware) carry
  // the HTTP call that produced them; explicit domain events leave these null.
  method?: string | null;
  path?: string | null;
  status_code?: number | null;
  // `request` for middleware-captured calls, or a domain tag for explicit events.
  source?: string | null;
  ip?: string | null;
  outcome?: AuditOutcome | null;
  timestamp: string;
}

// GET /audit-logs query. Every param NARROWS the result; all are optional.
// `GET /audit-logs/export` takes the same shape (pagination is ignored there).
// The index signature keeps it assignable to the http layer's `query` map.
export interface AuditLogQuery {
  entity?: string;
  entity_id?: string;
  actor?: string;
  action?: string;
  source?: string;
  method?: string;
  outcome?: AuditOutcome;
  q?: string;
  date_from?: string;
  date_to?: string;
  page?: number;
  page_size?: number;
  [k: string]: string | number | boolean | undefined;
}

export interface Notification extends BaseDoc {
  user_id: string;
  /** Dotted event type, e.g. `inventory.low_stock`, `order.dispatched`. */
  type: string;
  title: string;
  /** Optional on the wire (the model allows null). */
  body?: string | null;
  /**
   * Event payload. Carries the ids a deep link needs (`outlet_id`, `order_id`,
   * `warehouse_id`, `sku_id`, `payment_id`, …) plus a `route` that is written
   * for the FIELD app's route table — never navigate on it here, see
   * `src/lib/notifications.ts`.
   */
  data?: Record<string, unknown>;
  read: boolean;
}

/**
 * GET /notifications response. NOT a `Paginated<T>`: the backend takes a `limit`
 * (1..200) and returns the newest slice plus the caller's total unread count —
 * there is no page/page_size/total on this endpoint.
 */
export interface NotificationList {
  items: Notification[];
  unread_count: number;
}

// ---------- analytics (§4) ----------
// The `*_prev` companions are the same window in the previous month (1st to the
// same day-of-month), so a growth arrow compares like with like. They are
// optional on the view type: an older backend simply omits them and the UI
// renders the KPI without a growth chip rather than inventing one.
export interface AnalyticsSummary {
  coverage_pct: number;
  coverage_pct_prev?: number;
  strike_rate_pct: number;
  strike_rate_pct_prev?: number;
  sales_mtd: number;
  sales_prev?: number;
  outstanding_total: number;
  outstanding_overdue?: number;
  active_outlets?: number;
  pending_approvals?: number;
  visits_mtd?: number;
  visits_prev?: number;
  orders_mtd?: number;
  orders_prev?: number;
}

export interface SalesGroupRow {
  key: string;
  label: string;
  current: number;
  prior: number;
  growth_pct: number;
}

export interface SalesAnalytics {
  group_by: 'sku' | 'rep' | 'region' | 'category';
  rows: SalesGroupRow[];
  current_total: number;
  prior_total: number;
  growth_pct: number;
}

// One point per day, month-to-date, ascending. `coverage_pct` is CUMULATIVE:
// distinct outlets visited up to and including that day over active outlets, so
// the trend only ever climbs within a month instead of sawtoothing daily.
export interface CoveragePoint {
  date: string;
  visited: number;
  active_outlets: number;
  coverage_pct: number;
}

export interface CoverageRepRow {
  rep_id: string;
  rep_name: string;
  assigned_outlets: number;
  visited: number;
  coverage_pct: number;
}

export interface CoverageAnalytics {
  overall_coverage_pct: number;
  outlet_coverage_pct: number;
  series: CoveragePoint[];
  by_rep: CoverageRepRow[];
}

// Strike-rate series IS per-day (not cumulative): it is a daily conversion rate,
// not a running total.
export interface StrikeRatePoint {
  date: string;
  visits: number;
  productive: number;
  strike_rate_pct: number;
}

export interface StrikeRateRow {
  rep_id: string;
  rep_name: string;
  visits: number;
  productive: number;
  strike_rate_pct: number;
}

export interface StrikeRateAnalytics {
  overall_pct: number;
  visits: number;
  productive: number;
  series: StrikeRatePoint[];
  by_rep: StrikeRateRow[];
}

export interface LiveOpsRep {
  rep_id: string;
  rep_name: string;
  visits_today: number;
  planned_today: number;
  route_progress_pct: number;
  last_location?: GeoPoint | null;
  last_seen_at?: string | null;
  // Last outlet the rep checked into today (null before the first check-in).
  last_outlet_id?: string | null;
  last_outlet_name?: string | null;
  status: 'active' | 'idle' | 'offline';
}

export interface LiveOps {
  reps: LiveOpsRep[];
  server_time: string;
}

// ---------- auth (§4) ----------
export interface LoginResponse {
  access_token: string;
  token_type: 'bearer';
  user: User;
}

// ============================================================================
// STORE workspace — D2C store (STORE_CONTRACT.md §3 enums, §4 model, §6.9 DTOs)
// All money on the wire is integer paise (§0.1); `*_paise` fields are canonical,
// the bare INR companions (`price`, `total`, …) are derived display-only.
// ============================================================================

// ---------- store enums (§3) ----------
export type StoreOrderStatus =
  | 'created'
  | 'pending_payment'
  | 'paid'
  | 'confirmed'
  | 'packed'
  | 'shipped'
  | 'delivered'
  | 'payment_failed'
  | 'cancelled'
  | 'refunded';

export type CouponType = 'percent' | 'fixed' | 'free_shipping';
export type CouponRedemptionStatus = 'reserved' | 'confirmed' | 'released' | 'refunded';
export type PaymentProvider = 'razorpay';
export type PaymentStatus =
  | 'created'
  | 'authorized'
  | 'captured'
  | 'failed'
  | 'refunded'
  | 'partially_refunded';
export type CustomerStatus = 'active' | 'blocked';
export type StockAlertStatus = 'pending' | 'notified' | 'cancelled';
export type ShipmentStatus = 'pending' | 'packed' | 'shipped' | 'delivered' | 'returned';
export type StoreProductStatus = 'draft' | 'published' | 'archived';
export type ServiceabilityMode = 'all' | 'list' | 'prefix';
export type CouponScope = 'all' | 'category' | 'product';

// ---------- address (§4.1) ----------
export interface Address {
  id?: string;
  label?: string | null;
  name: string;
  phone: string;
  line1: string;
  line2?: string | null;
  city: string;
  state: string;
  pincode: string;
  is_default?: boolean;
}

// ---------- store products (§4.2 + §6.9 StoreProductAdmin) ----------
export interface StoreProductAdmin extends BaseDoc {
  sku_id: string;
  slug: string;
  name: string;
  subtitle?: string | null;
  description: string;
  category: string;
  price_paise: number;
  price: number;
  compare_at_price_paise?: number | null;
  compare_at_price?: number | null;
  currency: string;
  images: string[];
  og_image?: string | null;
  status: StoreProductStatus;
  featured: boolean;
  is_hero: boolean;
  badges: string[];
  sort_order: number;
  max_qty_per_order?: number | null;
  low_stock_threshold?: number | null;
  seo_title?: string | null;
  seo_description?: string | null;
  canonical_path?: string | null;
  gtin?: string | null;
  brand: string;
  review_source?: string | null;
  rating_avg?: number | null;
  rating_count?: number | null;
  // joined from `skus`
  sku_code?: string;
  sku_name?: string;
  pack_size?: string;
  unit?: string;
  // joined from `inventory` at fulfillment_warehouse_id
  qty_available?: number;
  qty_reserved?: number;
  sellable_qty?: number;
  in_stock?: boolean;
  low_stock?: boolean;
}

// §6.9 — create/PATCH body. `price`/`compare_at_price` are entered + sent in INR;
// the backend converts once to `*_paise` on write (§0.1). Flags go via /flags.
export interface StoreProductInput {
  sku_id: string;
  name: string;
  subtitle?: string;
  description: string;
  category: string;
  price: number; // INR
  compare_at_price?: number | null; // INR
  images?: string[];
  og_image?: string | null;
  slug?: string;
  badges?: string[];
  max_qty_per_order?: number | null;
  low_stock_threshold?: number | null;
  seo_title?: string;
  seo_description?: string;
  canonical_path?: string;
  gtin?: string;
}

export interface StoreProductFlagsInput {
  featured?: boolean;
  is_hero?: boolean;
  badges?: string[];
  sort_order?: number;
}

// ---------- store recipes (RECIPES_CONTRACT §1 model + §3 admin API) ----------
export type RecipeStatus = 'draft' | 'published';
export type RecipeDifficulty = 'Easy' | 'Medium' | 'Involved';

export interface RecipeIngredientGroup {
  heading: string | null; // e.g. "For the tadka" — null = single ungrouped list
  items: string[]; // display lines, e.g. "2 tbsp Organikaly Yellow Mustard Oil"
}

export interface RecipeAdmin extends BaseDoc {
  slug: string;
  title: string;
  subtitle?: string | null;
  recipe_type: string; // display key == label, e.g. "Dals & Curries"
  description: string;
  hero_image: string; // absolute URL
  og_image?: string | null; // falls back to hero_image
  video_url?: string | null; // optional how-to video (S3)
  prep_min: number;
  cook_min: number;
  servings: number;
  difficulty: string; // Easy | Medium | Involved
  ingredients: RecipeIngredientGroup[];
  steps: string[];
  tips: string[];
  tags: string[]; // JSON-LD keywords
  related_product_slugs: string[]; // storefront product slugs
  author: string;
  status: RecipeStatus;
  featured: boolean;
  sort_order: number;
  seo_title?: string | null; // brand-free — the site appends "· Organikaly"
  seo_description?: string | null;
}

// Create/PATCH body — slug/title/recipe_type required on create, PATCH is
// Partial<RecipeInput> (model_dump(exclude_unset=True) server-side).
export interface RecipeInput {
  slug: string;
  title: string;
  recipe_type: string;
  subtitle?: string | null;
  description?: string;
  hero_image?: string;
  og_image?: string | null;
  video_url?: string | null;
  prep_min?: number;
  cook_min?: number;
  servings?: number;
  difficulty?: string;
  ingredients?: RecipeIngredientGroup[];
  steps?: string[];
  tips?: string[];
  tags?: string[];
  related_product_slugs?: string[];
  author?: string;
  featured?: boolean;
  sort_order?: number;
  seo_title?: string | null;
  seo_description?: string | null;
}

// ---------- store reviews (REVIEWS_CONTRACT §1 model + §4 admin API) ----------
export type ReviewStatus = 'pending' | 'published' | 'rejected';

export interface StoreReviewAdmin {
  id: string;
  product_slug: string;
  product_name: string;
  customer_name: string;
  rating: number; // 1..5
  title?: string | null;
  body: string;
  verified_purchase: boolean;
  status: ReviewStatus;
  admin_note?: string | null;
  created_at: string;
}

// ---------- store orders (§4.5, §5.6 StoreOrderView, §6.9 StoreOrderAdmin) ----------
export interface StoreLineItem {
  store_product_id: string;
  sku_id: string;
  name: string;
  slug: string;
  image?: string | null;
  category: string;
  qty: number;
  unit_price_paise: number;
  unit_price?: number;
  line_total_paise: number;
  line_total?: number;
}

export interface Shipment {
  status: ShipmentStatus;
  courier?: string | null;
  awb?: string | null;
  tracking_url?: string | null;
  packed_at?: string | null;
  shipped_at?: string | null;
  delivered_at?: string | null;
  returned_at?: string | null;
}

export interface RefundEvent {
  refund_id: string;
  amount_paise: number;
  status: string;
  at: string;
}

export interface StoreStatusEntry {
  status: StoreOrderStatus;
  at: string;
  by: string;
  note?: string | null;
}

export interface StorePaymentEventRef {
  event_id: string;
  event_type: string;
  processing_state: string;
  received_at: string;
}

export interface StoreOrderView {
  id: string;
  code: string;
  status: StoreOrderStatus;
  payment_status: PaymentStatus;
  items: StoreLineItem[];
  subtotal_paise: number;
  subtotal: number;
  coupon_code?: string | null;
  coupon_discount_paise: number;
  coupon_discount?: number;
  shipping_fee_paise: number;
  shipping_fee?: number;
  total_paise: number;
  total: number;
  currency: string;
  shipping_address: Address;
  shipment: Shipment;
  refund_total_paise: number;
  created_at: string;
  paid_at?: string | null;
}

export interface StoreOrderAdmin extends StoreOrderView {
  customer_id: string;
  customer_name?: string;
  customer_email?: string;
  provider?: PaymentProvider;
  razorpay_order_id?: string | null;
  razorpay_payment_id?: string | null;
  razorpay_signature?: string | null;
  refund_events: RefundEvent[];
  refund_reason?: string | null;
  status_history: StoreStatusEntry[];
  needs_reconciliation: boolean;
  reconciliation_reason?: string | null;
  swept: boolean;
  warehouse_id: string;
  payment_expires_at?: string | null;
  notes?: string | null;
  payment_events: StorePaymentEventRef[];
}

// ---------- coupons (§4.4) ----------
// The coupon read view returns BOTH the canonical `*_paise` fields and the
// INR-named display companions (`amount_off`, `max_discount`, `min_order_value`).
export interface Coupon extends BaseDoc {
  code: string;
  type: CouponType;
  percent_off?: number | null;
  amount_off_paise?: number | null;
  amount_off?: number | null;
  max_discount_paise?: number | null;
  max_discount?: number | null;
  min_order_value_paise: number;
  min_order_value?: number;
  applies_to: CouponScope;
  category?: string | null;
  product_ids: string[];
  starts_at?: string | null;
  ends_at?: string | null;
  usage_limit?: number | null;
  usage_limit_per_customer?: number | null;
  used_count: number;
  active: boolean;
  description?: string | null;
}

// Coupon endpoints speak INR on input: send `amount_off` / `max_discount` /
// `min_order_value` as INR numbers; the backend converts to `*_paise` on write.
// `percent_off` stays an integer percent.
export interface CouponInput {
  code: string;
  type: CouponType;
  percent_off?: number | null;
  amount_off?: number | null;
  max_discount?: number | null;
  min_order_value?: number;
  applies_to?: CouponScope;
  category?: string | null;
  product_ids?: string[];
  starts_at?: string | null;
  ends_at?: string | null;
  usage_limit?: number | null;
  usage_limit_per_customer?: number | null;
  active?: boolean;
  description?: string | null;
}

// ---------- customers (§4.1, §6.9 CustomerAdmin) ----------
export interface CustomerOrderSummary {
  order_count: number;
  lifetime_value_paise: number;
  lifetime_value: number;
  last_order_at?: string | null;
}

export interface CustomerAdmin {
  id: string;
  name: string;
  email: string;
  phone?: string | null;
  email_verified: boolean;
  status: CustomerStatus;
  marketing_opt_in: boolean;
  addresses: Address[];
  default_address_id?: string | null;
  created_at: string;
  last_login_at?: string | null;
  order_summary: CustomerOrderSummary;
}

// ---------- store config (§4.8) ----------
export interface StoreConfig {
  id: string;
  store_enabled: boolean;
  fulfillment_warehouse_id: string;
  currency: string;
  flat_fee_paise: number;
  free_shipping_threshold_paise: number;
  serviceability_mode: ServiceabilityMode;
  serviceable_pincodes: string[];
  serviceable_pincode_prefixes: string[];
  low_stock_threshold: number;
  razorpay_key_id?: string | null;
  support_email: string;
  support_phone?: string | null;
  order_prefix: string;
  payment_ttl_min: number;
}

export type StoreConfigInput = Partial<Omit<StoreConfig, 'id'>>;

// ---------- stock alerts (§4.7, §6.9 StockAlertAdmin) ----------
export interface StockAlertAdmin {
  id: string;
  email: string;
  store_product_id: string;
  product_name?: string;
  sku_id: string;
  sku_code?: string;
  status: StockAlertStatus;
  is_open: boolean;
  customer_id?: string | null;
  created_at: string;
  notified_at?: string | null;
}

// ---------- store analytics summary (§6.8) ----------
export interface StoreTopProduct {
  store_product_id: string;
  name: string;
  qty: number;
  revenue_paise: number;
}

export interface StoreLowStockItem {
  store_product_id: string;
  sku_code: string;
  sellable_qty: number;
}

export interface StoreRecentOrder {
  code: string;
  total_paise: number;
  status: StoreOrderStatus;
  created_at: string;
}

export interface StoreAnalyticsSummary {
  revenue_paise: number;
  revenue: number;
  orders: number;
  aov_paise: number;
  aov: number;
  paid_orders: number;
  pending_fulfilment: number;
  refunds: number;
  refund_total_paise: number;
  top_products: StoreTopProduct[];
  low_stock: StoreLowStockItem[];
  recent_orders: StoreRecentOrder[];
}

// ============================================================================
// Organikaly Club — Membership, Coins Wallet & Push (MEMBERSHIP_CONTRACT §1, §8)
// Admin DTOs mirrored from §8. All money is integer paise (`*_paise` canonical),
// with a bare INR companion (`price`, `membership_revenue`, …) for display only.
// Coins are whole integers.
// ============================================================================

// ---------- enums (§1) ----------
export type MembershipStatus = 'pending' | 'active' | 'expired' | 'cancelled';
export type CoinReason =
  | 'earn'
  | 'redeem'
  | 'redeem_release'
  | 'welcome_bonus'
  | 'admin_adjust'
  | 'refund_reversal'
  | 'renewal_bonus';
export type PushPlatform = 'ios' | 'android' | 'web';
export type PushSegment = 'all' | 'members' | 'non_members' | 'customer_ids';

// ---------- membership admin (§8 MembershipAdmin) ----------
export interface MembershipCustomerRef {
  id: string;
  name: string;
  email: string;
  phone?: string | null;
}

export interface MembershipAdmin {
  id: string;
  customer_id: string;
  customer: MembershipCustomerRef;
  plan_id?: string;
  plan_name: string;
  price_paise: number;
  price: number;
  status: MembershipStatus;
  started_at?: string | null;
  expires_at?: string | null;
  days_remaining?: number | null;
  auto_renew: boolean;
  is_renewal: boolean;
  payment_status?: PaymentStatus;
  razorpay_order_id?: string | null;
  razorpay_payment_id?: string | null;
  wallet_balance_coins: number;
  created_at: string;
  updated_at?: string;
}

// ---------- coin wallet + ledger (§2.3 / §2.4, §7 WalletView) ----------
export interface CoinLedgerEntry {
  delta_coins: number;
  reason: CoinReason;
  balance_after: number;
  store_order_id?: string | null;
  membership_id?: string | null;
  note?: string | null;
  // WalletView ledger rows carry `at`; some admin payloads use `created_at`.
  at?: string;
  created_at?: string;
}

export interface WalletAdmin {
  balance_coins: number;
  ledger: CoinLedgerEntry[];
}

// ---------- membership plan (§2.1, §8 MembershipPlanAdmin) ----------
export interface MembershipPlanAdmin {
  id: string;
  name: string;
  slug: string;
  price_paise: number;
  price: number;
  duration_days: number;
  free_delivery_for_members: boolean;
  member_discount_bps: number;
  member_discount_pct: number;
  coin_earn_paise_per_coin: number;
  member_earn_multiplier_pct: number;
  coin_redeem_value_paise: number;
  non_member_redeem_pct: number;
  max_redeem_pct_of_order: number;
  welcome_coins: number;
  renewal_bonus_coins: number;
  benefits: string[];
  active: boolean;
  created_at?: string;
  updated_at?: string;
}

// §8 MembershipPlanInput — `price` is entered/sent in INR (backend → paise);
// the `*_paise` coin-rate fields are sent as integer paise directly.
export interface MembershipPlanInput {
  name: string;
  price: number; // INR
  duration_days: number;
  free_delivery_for_members: boolean;
  member_discount_bps: number;
  coin_earn_paise_per_coin: number; // paise
  member_earn_multiplier_pct: number;
  coin_redeem_value_paise: number; // paise
  non_member_redeem_pct: number;
  max_redeem_pct_of_order: number;
  welcome_coins: number;
  renewal_bonus_coins: number;
  benefits: string[];
  active: boolean;
}

// ---------- membership analytics (§8 MembershipAnalytics) ----------
export interface MembershipRecentMember {
  id: string;
  customer_name: string;
  status: MembershipStatus;
  expires_at?: string | null;
  created_at: string;
}

export interface MembershipAnalytics {
  active_members: number;
  pending: number;
  expired: number;
  cancelled: number;
  new_this_period: number;
  expiring_30d: number;
  membership_revenue_paise: number;
  membership_revenue: number;
  mrr_paise?: number | null;
  mrr?: number | null;
  arpu_paise?: number | null;
  churn_rate?: number | null;
  coins_outstanding: number;
  recent_members: MembershipRecentMember[];
}

// ---------- push campaigns + devices (§2.5 / §2.7, §8 PushCampaignAdmin) ----------
export interface PushReceipt {
  token: string;
  status: string;
  error?: string | null;
}

export interface PushCampaignAdmin {
  id: string;
  title: string;
  body: string;
  deep_link?: string | null;
  data: Record<string, unknown>;
  segment: PushSegment;
  customer_ids: string[];
  sent_by: string;
  sent_by_name?: string | null;
  target_count: number;
  accepted_count: number;
  failed_count: number;
  status: string; // queued | sent | error
  error?: string | null;
  receipts: PushReceipt[];
  created_at: string;
}

// §8 POST /push/campaigns body.
export interface PushCampaignInput {
  title: string;
  body: string;
  deep_link?: string | null;
  data?: Record<string, unknown>;
  segment: PushSegment;
  customer_ids?: string[];
}

export interface PushDeviceAdmin {
  id: string;
  customer_id: string;
  customer_name?: string | null;
  platform: PushPlatform;
  enabled: boolean;
  device_name?: string | null;
  last_seen_at: string;
}

// ---------- Learn / Guides (LEARN_CONTRACT §2–§4) ----------
// The catalog is split by `audience`, server-side: the public API can only ever
// return "public" videos; the admin API only "admin" videos, with a presigned
// (TTL 6h) playback URL minted per request.
export type LearnAudience = 'public' | 'admin';
export type LearnTrack = 'field' | 'admin' | 'store';
export type LearnLevel = 'beginner' | 'intermediate' | 'advanced';

/** Derived from the voiceover manifest — never hand-written, so it cannot drift. */
export interface LearnChapter {
  start_sec: number;
  end_sec: number;
  title: string; // on-screen caption for the scene
  narration: string; // what is actually said
}

/** VideoCard (§3) — the list/grid shape. */
export interface LearnVideoCard {
  slug: string;
  track: LearnTrack;
  module: string;
  sequence: number; // 1-based curriculum order within the track (gaps allowed)
  title: string;
  summary: string;
  duration_sec: number;
  poster_url?: string | null;
  tags: string[];
  level: LearnLevel;
}

/** VideoDetail (§3) = VideoCard + description, chapters, transcript, video_url. */
export interface LearnVideoDetail extends LearnVideoCard {
  description: string;
  chapters: LearnChapter[];
  transcript: string;
  /** Absolute for public videos; presigned + short-lived for admin videos. */
  video_url?: string | null;
}

/** GET /learn[/admin]/videos/{slug} — prev/next walk the same track by sequence. */
export interface LearnVideoDetailResponse {
  video: LearnVideoDetail;
  prev: LearnVideoCard | null;
  next: LearnVideoCard | null;
}

/** GET /learn[/admin]/videos */
export interface LearnVideoList {
  items: LearnVideoCard[];
  total: number;
}

/** GET /learn[/admin]/tracks */
export interface LearnTrackSummary {
  track: LearnTrack;
  label: string;
  blurb: string;
  video_count: number;
  total_duration_sec: number;
}
